"""ClawRadar 阶段一 ingest、阶段二 score、阶段三 write、阶段四 deliver、阶段五 orchestrator 与通知入口。"""

from .contracts import (
    ErrorCode,
    IngestRunStatus,
    IngestValidationError,
    normalize_ingest_payload,
    validate_ingest_payload,
)
from .delivery import (
    DeliveryChannel,
    DeliveryErrorCode,
    DeliveryRunStatus,
    DeliveryValidationError,
    build_delivery_rejection,
    build_feishu_delivery_message,
    topic_radar_deliver,
    validate_delivery_payload,
)
from .notifications import (
    NotificationChannel,
    NotificationErrorCode,
    NotificationReason,
    NotificationRunStatus,
    NotificationValidationError,
    build_notification_payload,
    build_notification_rejection,
    build_notification_summary,
    sanitize_notification_payload,
    topic_radar_notify,
)
from .orchestrator import (
    OrchestratorErrorCode,
    OrchestratorExecutionMode,
    OrchestratorRunStatus,
    OrchestratorStageStatus,
    topic_radar_orchestrate,
)
from .scoring import (
    SCORE_WEIGHTS,
    ScoreDecisionStatus,
    ScoreDimension,
    ScoreErrorCode,
    ScoreRunStatus,
    ScoreValidationError,
    build_score_rejection,
    score_topic_candidates,
    validate_score_payload,
)
from .writing import (
    WriteErrorCode,
    WriteExecutor,
    WriteOperation,
    WriteRunStatus,
    WriteValidationError,
    build_write_rejection,
    topic_radar_write,
    validate_write_payload,
)
from .real_source import RealSourceUnavailableError
from .topics import (
    TopicCardStatus,
    TopicRunStatus,
    UserTopicValidationError,
    build_crawl_results,
    build_topic_cards,
    load_user_topic_payload,
    topic_cards_to_score_payload,
)

__all__ = [
    "ErrorCode",
    "IngestRunStatus",
    "IngestValidationError",
    "normalize_ingest_payload",
    "validate_ingest_payload",
    "DeliveryChannel",
    "DeliveryErrorCode",
    "DeliveryRunStatus",
    "DeliveryValidationError",
    "build_delivery_rejection",
    "build_feishu_delivery_message",
    "topic_radar_deliver",
    "validate_delivery_payload",
    "NotificationChannel",
    "NotificationErrorCode",
    "NotificationReason",
    "NotificationRunStatus",
    "NotificationValidationError",
    "build_notification_payload",
    "build_notification_rejection",
    "build_notification_summary",
    "sanitize_notification_payload",
    "topic_radar_notify",
    "OrchestratorErrorCode",
    "OrchestratorExecutionMode",
    "OrchestratorRunStatus",
    "OrchestratorStageStatus",
    "topic_radar_orchestrate",
    "SCORE_WEIGHTS",
    "ScoreDecisionStatus",
    "ScoreDimension",
    "ScoreErrorCode",
    "ScoreRunStatus",
    "ScoreValidationError",
    "build_score_rejection",
    "score_topic_candidates",
    "validate_score_payload",
    "WriteErrorCode",
    "WriteExecutor",
    "WriteOperation",
    "WriteRunStatus",
    "WriteValidationError",
    "build_write_rejection",
    "topic_radar_write",
    "validate_write_payload",
    "RealSourceUnavailableError",
    "TopicCardStatus",
    "TopicRunStatus",
    "UserTopicValidationError",
    "build_crawl_results",
    "build_topic_cards",
    "load_user_topic_payload",
    "topic_cards_to_score_payload",
]

