"""OpenClaw P0 阶段一 ingest、阶段二 score、阶段三 write、阶段四 deliver 与阶段五 orchestrator 能力入口。"""

from .contracts import (
    ErrorCode,
    IngestRunStatus,
    IngestValidationError,
    normalize_ingest_payload,
    validate_ingest_payload,
)
from .delivery import (
    DeliveryChannel,
    DeliveryErrorCode,
    DeliveryRunStatus,
    DeliveryValidationError,
    build_delivery_rejection,
    build_feishu_delivery_message,
    topic_radar_deliver,
    validate_delivery_payload,
)
from .orchestrator import (
    OrchestratorErrorCode,
    OrchestratorExecutionMode,
    OrchestratorRunStatus,
    OrchestratorStageStatus,
    topic_radar_orchestrate,
)
from .scoring import (
    SCORE_WEIGHTS,
    ScoreDecisionStatus,
    ScoreDimension,
    ScoreErrorCode,
    ScoreRunStatus,
    ScoreValidationError,
    build_score_rejection,
    score_topic_candidates,
    validate_score_payload,
)
from .writing import (
    WriteErrorCode,
    WriteExecutor,
    WriteOperation,
    WriteRunStatus,
    WriteValidationError,
    build_write_rejection,
    topic_radar_write,
    validate_write_payload,
)

__all__ = [
    "ErrorCode",
    "IngestRunStatus",
    "IngestValidationError",
    "normalize_ingest_payload",
    "validate_ingest_payload",
    "DeliveryChannel",
    "DeliveryErrorCode",
    "DeliveryRunStatus",
    "DeliveryValidationError",
    "build_delivery_rejection",
    "build_feishu_delivery_message",
    "topic_radar_deliver",
    "validate_delivery_payload",
    "OrchestratorErrorCode",
    "OrchestratorExecutionMode",
    "OrchestratorRunStatus",
    "OrchestratorStageStatus",
    "topic_radar_orchestrate",
    "SCORE_WEIGHTS",
    "ScoreDecisionStatus",
    "ScoreDimension",
    "ScoreErrorCode",
    "ScoreRunStatus",
    "ScoreValidationError",
    "build_score_rejection",
    "score_topic_candidates",
    "validate_score_payload",
    "WriteErrorCode",
    "WriteExecutor",
    "WriteOperation",
    "WriteRunStatus",
    "WriteValidationError",
    "build_write_rejection",
    "topic_radar_write",
    "validate_write_payload",
]
